### ISSUE TITLE
Release 1.0.0

### ISSUE THREAD

**Issue by ro0NL** [thephpleague/oauth2-server-bundle#199]
would be nice to have 1.x stable

> Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable. (https://semver.org/)

**Comment by glennmcewan** [comment]
It would be great to have an idea of what's left on the roadmap for v1 even if there's no time estimate; we're looking to move away from Trikoder as soon as this is marked as stable.

**Comment by ro0NL** [comment]
alternatively, perhaps shadow the current library version. meaning start from `9.x` here

**Comment by ro0NL** [comment]
@glennmcewan it runs in prod, it's stable.

cc @chalasr

**Comment by djsunderland** [comment]
@ro0NL can you share what kind of production environment(s) it is running on?

We are looking to move our SaaS financial services CRM to this and therefore its mission critical it functions at scale.

**Comment by ajgarlag** [comment]
Before tagging v1.0, I'd like to propose a PR to rename the `NullUser` class. I think this class should be renamed to `ClientUser` or `ClientCredentialsUser` and that the `getUserIdentifier` method should return the client ID. Returning an empty string has been deprecated since Symfony 7.2 (https://github.com/symfony/symfony/pull/58007). What do you think?
